ERROR_NO_SUCH_PROFILE = 1
ERROR_INCORRECT_PASSWORD = 2
ERROR_NO_SUCH_LISTING = 3
ERROR_INCORRECT_LISTING_OWNERSHIP = 4
ERROR_EMAIL_IN_USE = 5
ERROR_NO_BID_MADE = 6
ERROR_BID_DOES_NOT_EXIST = 7
ERROR_INVALID_SERVER_REQUEST = 8